services:
  web-my-kinsen:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
      args:
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        BETTER_AUTH_URL: ${BETTER_AUTH_URL}
        MAILTRAP_CLIENT_TOKEN: ${MAILTRAP_CLIENT_TOKEN}
        DATABASE_URL: ${DATABASE_URL}
    container_name: web-my-kinsen
    restart: always
    ports:
      - 3002:3000
    networks:
      - web_my_kinsen
    depends_on:
      - adminer

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: syahrulmykinsen
      POSTGRES_USER: syahrul
      POSTGRES_DB: my-kinsen
    ports:
      - 5432:5432
    networks:
      - web_my_kinsen

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - web_my_kinsen
    depends_on:
      - db

networks:
  web_my_kinsen:
    # Specify driver options
    driver: bridge
