services:
  web-my-kinsen:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    container_name: web-my-kinsen
    restart: always
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
    ports:
      - "3002:3000"
    depends_on:
      - adminer

  db:
    image: postgres
    container_name: db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: syahrulmykinsen
      POSTGRES_USER: syahrul
      POSTGRES_DB: my-kinsen

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
