services:
  web-my-kinsen:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    container_name: web-my-kinsen
    restart: always
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
    ports:
      - 3002:3000
    depends_on:
      - adminer

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: syahrulmykinsen
      POSTGRES_USER: syahrul
      POSTGRES_DB: my-kinsen
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
