name: My Kinsen Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build Project

    strategy:
      matrix:
        node-version: [22]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm run install
      run: pnpm run build

  # docker-image:

  #   runs-on: ubuntu-latest
  #   name: Build Docker Image
  #   needs: [build]

  #   strategy:
  #   matrix:
  #     node-version: [22]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: 10

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'pnpm'

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build the Docker image & Push to DockerHub
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: docker/staging/Dockerfile
  #         push: true
  #         platforms: linux/amd64
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-kinsen:$(date +%s),${{ secrets.DOCKERHUB_USERNAME }}/my-kinsen:latest
  #         build-args: |
  #           APP_VERSION=0.0.10
